<script setup lang="ts">
import { http, HttpResponse } from 'msw'

const schema = '/api/custom_forms/1/definition'

useMockRequest(
    http.get('*/api/custom_forms/1/definition', () => {
        return HttpResponse.json({
            title: '',
            type: 'object',
            properties: {
                'nom': {
                    type: 'string',
                    title: 'Nom',
                    attr: {
                        'data-group': null,
                        'placeholder': 'Votre nom',
                    },
                    propertyOrder: 1,
                },
                'prenom': {
                    type: 'string',
                    title: 'Pr\u00e9nom',
                    attr: {
                        'data-group': null,
                        'placeholder': 'Votre pr\u00e9nom',
                        'autocomplete': 'given-name',
                    },
                    propertyOrder: 2,
                },
                'adresse_email': {
                    type: 'string',
                    title: 'Adresse email',
                    attr: {
                        'data-group': null,
                        'autocomplete': 'email',
                    },
                    widget: 'email',
                    propertyOrder: 3,
                },
                'pays': {
                    enum: [
                        'AF',
                        'ZA',
                        'AL',
                        'DZ',
                        'DE',
                        'AD',
                        'AO',
                        'AI',
                        'AQ',
                        'AG',
                        'SA',
                        'AR',
                        'AM',
                        'AW',
                        'AU',
                        'AT',
                        'AZ',
                        'BS',
                        'BH',
                        'BD',
                        'BB',
                        'BE',
                        'BZ',
                        'BJ',
                        'BM',
                        'BT',
                        'BY',
                        'BO',
                        'BA',
                        'BW',
                        'BR',
                        'BN',
                        'BG',
                        'BF',
                        'BI',
                        'KH',
                        'CM',
                        'CA',
                        'CV',
                        'CL',
                        'CN',
                        'CY',
                        'CO',
                        'KM',
                        'CG',
                        'CD',
                        'KP',
                        'KR',
                        'CR',
                        'CI',
                        'HR',
                        'CU',
                        'CW',
                        'DK',
                        'DJ',
                        'DM',
                        'EG',
                        'AE',
                        'EC',
                        'ER',
                        'ES',
                        'EE',
                        'SZ',
                        'VA',
                        'US',
                        'ET',
                        'FJ',
                        'FI',
                        'FR',
                        'GA',
                        'GM',
                        'GE',
                        'GS',
                        'GH',
                        'GI',
                        'GR',
                        'GD',
                        'GL',
                        'GP',
                        'GU',
                        'GT',
                        'GG',
                        'GN',
                        'GQ',
                        'GW',
                        'GY',
                        'GF',
                        'HT',
                        'HN',
                        'HU',
                        'BV',
                        'CX',
                        'IM',
                        'NF',
                        'AX',
                        'KY',
                        'CC',
                        'CK',
                        'FO',
                        'HM',
                        'FK',
                        'MP',
                        'MH',
                        'UM',
                        'PN',
                        'SB',
                        'TC',
                        'VG',
                        'VI',
                        'IN',
                        'ID',
                        'IQ',
                        'IR',
                        'IE',
                        'IS',
                        'IL',
                        'IT',
                        'JM',
                        'JP',
                        'JE',
                        'JO',
                        'KZ',
                        'KE',
                        'KG',
                        'KI',
                        'KW',
                        'RE',
                        'LA',
                        'LS',
                        'LV',
                        'LB',
                        'LR',
                        'LY',
                        'LI',
                        'LT',
                        'LU',
                        'MK',
                        'MG',
                        'MY',
                        'MW',
                        'MV',
                        'ML',
                        'MT',
                        'MA',
                        'MQ',
                        'MU',
                        'MR',
                        'YT',
                        'MX',
                        'FM',
                        'MD',
                        'MC',
                        'MN',
                        'ME',
                        'MS',
                        'MZ',
                        'MM',
                        'NA',
                        'NR',
                        'NP',
                        'NI',
                        'NE',
                        'NG',
                        'NU',
                        'NO',
                        'NC',
                        'NZ',
                        'OM',
                        'UG',
                        'UZ',
                        'PK',
                        'PW',
                        'PA',
                        'PG',
                        'PY',
                        'NL',
                        'BQ',
                        'PE',
                        'PH',
                        'PL',
                        'PF',
                        'PR',
                        'PT',
                        'QA',
                        'HK',
                        'MO',
                        'CF',
                        'DO',
                        'RO',
                        'GB',
                        'RU',
                        'RW',
                        'EH',
                        'BL',
                        'KN',
                        'SM',
                        'MF',
                        'SX',
                        'PM',
                        'VC',
                        'SH',
                        'LC',
                        'SV',
                        'WS',
                        'AS',
                        'ST',
                        'SN',
                        'RS',
                        'SC',
                        'SL',
                        'SG',
                        'SK',
                        'SI',
                        'SO',
                        'SD',
                        'SS',
                        'LK',
                        'SE',
                        'CH',
                        'SR',
                        'SJ',
                        'SY',
                        'TJ',
                        'TW',
                        'TZ',
                        'TD',
                        'CZ',
                        'TF',
                        'IO',
                        'PS',
                        'TH',
                        'TL',
                        'TG',
                        'TK',
                        'TO',
                        'TT',
                        'TN',
                        'TM',
                        'TR',
                        'TV',
                        'UA',
                        'UY',
                        'VU',
                        'VE',
                        'VN',
                        'WF',
                        'YE',
                        'ZM',
                        'ZW',
                    ],
                    enum_titles: [
                        'Afghanistan',
                        'Afrique du Sud',
                        'Albanie',
                        'Alg\u00e9rie',
                        'Allemagne',
                        'Andorre',
                        'Angola',
                        'Anguilla',
                        'Antarctique',
                        'Antigua-et-Barbuda',
                        'Arabie saoudite',
                        'Argentine',
                        'Arm\u00e9nie',
                        'Aruba',
                        'Australie',
                        'Autriche',
                        'Azerba\u00efdjan',
                        'Bahamas',
                        'Bahre\u00efn',
                        'Bangladesh',
                        'Barbade',
                        'Belgique',
                        'Belize',
                        'B\u00e9nin',
                        'Bermudes',
                        'Bhoutan',
                        'Bi\u00e9lorussie',
                        'Bolivie',
                        'Bosnie-Herz\u00e9govine',
                        'Botswana',
                        'Br\u00e9sil',
                        'Brunei',
                        'Bulgarie',
                        'Burkina Faso',
                        'Burundi',
                        'Cambodge',
                        'Cameroun',
                        'Canada',
                        'Cap-Vert',
                        'Chili',
                        'Chine',
                        'Chypre',
                        'Colombie',
                        'Comores',
                        'Congo-Brazzaville',
                        'Congo-Kinshasa',
                        'Cor\u00e9e du Nord',
                        'Cor\u00e9e du Sud',
                        'Costa Rica',
                        'C\u00f4te d\u2019Ivoire',
                        'Croatie',
                        'Cuba',
                        'Cura\u00e7ao',
                        'Danemark',
                        'Djibouti',
                        'Dominique',
                        '\u00c9gypte',
                        '\u00c9mirats arabes unis',
                        '\u00c9quateur',
                        '\u00c9rythr\u00e9e',
                        'Espagne',
                        'Estonie',
                        'Eswatini',
                        '\u00c9tat de la Cit\u00e9 du Vatican',
                        '\u00c9tats-Unis',
                        '\u00c9thiopie',
                        'Fidji',
                        'Finlande',
                        'France',
                        'Gabon',
                        'Gambie',
                        'G\u00e9orgie',
                        'G\u00e9orgie du Sud-et-les \u00celes Sandwich du Sud',
                        'Ghana',
                        'Gibraltar',
                        'Gr\u00e8ce',
                        'Grenade',
                        'Groenland',
                        'Guadeloupe',
                        'Guam',
                        'Guatemala',
                        'Guernesey',
                        'Guin\u00e9e',
                        'Guin\u00e9e \u00e9quatoriale',
                        'Guin\u00e9e-Bissau',
                        'Guyana',
                        'Guyane fran\u00e7aise',
                        'Ha\u00efti',
                        'Honduras',
                        'Hongrie',
                        '\u00cele Bouvet',
                        '\u00cele Christmas',
                        '\u00cele de Man',
                        '\u00cele Norfolk',
                        '\u00celes \u00c5land',
                        '\u00celes Ca\u00efmans',
                        '\u00celes Cocos',
                        '\u00celes Cook',
                        '\u00celes F\u00e9ro\u00e9',
                        '\u00celes Heard-et-MacDonald',
                        '\u00celes Malouines',
                        '\u00celes Mariannes du Nord',
                        '\u00celes Marshall',
                        '\u00celes mineures \u00e9loign\u00e9es des \u00c9tats-Unis',
                        '\u00celes Pitcairn',
                        '\u00celes Salomon',
                        '\u00celes Turques-et-Ca\u00efques',
                        '\u00celes Vierges britanniques',
                        '\u00celes Vierges des \u00c9tats-Unis',
                        'Inde',
                        'Indon\u00e9sie',
                        'Irak',
                        'Iran',
                        'Irlande',
                        'Islande',
                        'Isra\u00ebl',
                        'Italie',
                        'Jama\u00efque',
                        'Japon',
                        'Jersey',
                        'Jordanie',
                        'Kazakhstan',
                        'Kenya',
                        'Kirghizstan',
                        'Kiribati',
                        'Kowe\u00eft',
                        'La R\u00e9union',
                        'Laos',
                        'Lesotho',
                        'Lettonie',
                        'Liban',
                        'Liberia',
                        'Libye',
                        'Liechtenstein',
                        'Lituanie',
                        'Luxembourg',
                        'Mac\u00e9doine du Nord',
                        'Madagascar',
                        'Malaisie',
                        'Malawi',
                        'Maldives',
                        'Mali',
                        'Malte',
                        'Maroc',
                        'Martinique',
                        'Maurice',
                        'Mauritanie',
                        'Mayotte',
                        'Mexique',
                        'Micron\u00e9sie',
                        'Moldavie',
                        'Monaco',
                        'Mongolie',
                        'Mont\u00e9n\u00e9gro',
                        'Montserrat',
                        'Mozambique',
                        'Myanmar (Birmanie)',
                        'Namibie',
                        'Nauru',
                        'N\u00e9pal',
                        'Nicaragua',
                        'Niger',
                        'Nigeria',
                        'Niue',
                        'Norv\u00e8ge',
                        'Nouvelle-Cal\u00e9donie',
                        'Nouvelle-Z\u00e9lande',
                        'Oman',
                        'Ouganda',
                        'Ouzb\u00e9kistan',
                        'Pakistan',
                        'Palaos',
                        'Panama',
                        'Papouasie-Nouvelle-Guin\u00e9e',
                        'Paraguay',
                        'Pays-Bas',
                        'Pays-Bas carib\u00e9ens',
                        'P\u00e9rou',
                        'Philippines',
                        'Pologne',
                        'Polyn\u00e9sie fran\u00e7aise',
                        'Porto Rico',
                        'Portugal',
                        'Qatar',
                        'R.A.S. chinoise de Hong Kong',
                        'R.A.S. chinoise de Macao',
                        'R\u00e9publique centrafricaine',
                        'R\u00e9publique dominicaine',
                        'Roumanie',
                        'Royaume-Uni',
                        'Russie',
                        'Rwanda',
                        'Sahara occidental',
                        'Saint-Barth\u00e9lemy',
                        'Saint-Christophe-et-Ni\u00e9v\u00e8s',
                        'Saint-Marin',
                        'Saint-Martin',
                        'Saint-Martin (partie n\u00e9erlandaise)',
                        'Saint-Pierre-et-Miquelon',
                        'Saint-Vincent-et-les Grenadines',
                        'Sainte-H\u00e9l\u00e8ne',
                        'Sainte-Lucie',
                        'Salvador',
                        'Samoa',
                        'Samoa am\u00e9ricaines',
                        'Sao Tom\u00e9-et-Principe',
                        'S\u00e9n\u00e9gal',
                        'Serbie',
                        'Seychelles',
                        'Sierra Leone',
                        'Singapour',
                        'Slovaquie',
                        'Slov\u00e9nie',
                        'Somalie',
                        'Soudan',
                        'Soudan du Sud',
                        'Sri Lanka',
                        'Su\u00e8de',
                        'Suisse',
                        'Suriname',
                        'Svalbard et Jan Mayen',
                        'Syrie',
                        'Tadjikistan',
                        'Ta\u00efwan',
                        'Tanzanie',
                        'Tchad',
                        'Tch\u00e9quie',
                        'Terres australes fran\u00e7aises',
                        'Territoire britannique de l\u2019oc\u00e9an Indien',
                        'Territoires palestiniens',
                        'Tha\u00eflande',
                        'Timor oriental',
                        'Togo',
                        'Tokelau',
                        'Tonga',
                        'Trinit\u00e9-et-Tobago',
                        'Tunisie',
                        'Turkm\u00e9nistan',
                        'Turquie',
                        'Tuvalu',
                        'Ukraine',
                        'Uruguay',
                        'Vanuatu',
                        'Venezuela',
                        'Vi\u00eat Nam',
                        'Wallis-et-Futuna',
                        'Y\u00e9men',
                        'Zambie',
                        'Zimbabwe',
                    ],
                    options: {
                        enum_titles: [
                            'Afghanistan',
                            'Afrique du Sud',
                            'Albanie',
                            'Alg\u00e9rie',
                            'Allemagne',
                            'Andorre',
                            'Angola',
                            'Anguilla',
                            'Antarctique',
                            'Antigua-et-Barbuda',
                            'Arabie saoudite',
                            'Argentine',
                            'Arm\u00e9nie',
                            'Aruba',
                            'Australie',
                            'Autriche',
                            'Azerba\u00efdjan',
                            'Bahamas',
                            'Bahre\u00efn',
                            'Bangladesh',
                            'Barbade',
                            'Belgique',
                            'Belize',
                            'B\u00e9nin',
                            'Bermudes',
                            'Bhoutan',
                            'Bi\u00e9lorussie',
                            'Bolivie',
                            'Bosnie-Herz\u00e9govine',
                            'Botswana',
                            'Br\u00e9sil',
                            'Brunei',
                            'Bulgarie',
                            'Burkina Faso',
                            'Burundi',
                            'Cambodge',
                            'Cameroun',
                            'Canada',
                            'Cap-Vert',
                            'Chili',
                            'Chine',
                            'Chypre',
                            'Colombie',
                            'Comores',
                            'Congo-Brazzaville',
                            'Congo-Kinshasa',
                            'Cor\u00e9e du Nord',
                            'Cor\u00e9e du Sud',
                            'Costa Rica',
                            'C\u00f4te d\u2019Ivoire',
                            'Croatie',
                            'Cuba',
                            'Cura\u00e7ao',
                            'Danemark',
                            'Djibouti',
                            'Dominique',
                            '\u00c9gypte',
                            '\u00c9mirats arabes unis',
                            '\u00c9quateur',
                            '\u00c9rythr\u00e9e',
                            'Espagne',
                            'Estonie',
                            'Eswatini',
                            '\u00c9tat de la Cit\u00e9 du Vatican',
                            '\u00c9tats-Unis',
                            '\u00c9thiopie',
                            'Fidji',
                            'Finlande',
                            'France',
                            'Gabon',
                            'Gambie',
                            'G\u00e9orgie',
                            'G\u00e9orgie du Sud-et-les \u00celes Sandwich du Sud',
                            'Ghana',
                            'Gibraltar',
                            'Gr\u00e8ce',
                            'Grenade',
                            'Groenland',
                            'Guadeloupe',
                            'Guam',
                            'Guatemala',
                            'Guernesey',
                            'Guin\u00e9e',
                            'Guin\u00e9e \u00e9quatoriale',
                            'Guin\u00e9e-Bissau',
                            'Guyana',
                            'Guyane fran\u00e7aise',
                            'Ha\u00efti',
                            'Honduras',
                            'Hongrie',
                            '\u00cele Bouvet',
                            '\u00cele Christmas',
                            '\u00cele de Man',
                            '\u00cele Norfolk',
                            '\u00celes \u00c5land',
                            '\u00celes Ca\u00efmans',
                            '\u00celes Cocos',
                            '\u00celes Cook',
                            '\u00celes F\u00e9ro\u00e9',
                            '\u00celes Heard-et-MacDonald',
                            '\u00celes Malouines',
                            '\u00celes Mariannes du Nord',
                            '\u00celes Marshall',
                            '\u00celes mineures \u00e9loign\u00e9es des \u00c9tats-Unis',
                            '\u00celes Pitcairn',
                            '\u00celes Salomon',
                            '\u00celes Turques-et-Ca\u00efques',
                            '\u00celes Vierges britanniques',
                            '\u00celes Vierges des \u00c9tats-Unis',
                            'Inde',
                            'Indon\u00e9sie',
                            'Irak',
                            'Iran',
                            'Irlande',
                            'Islande',
                            'Isra\u00ebl',
                            'Italie',
                            'Jama\u00efque',
                            'Japon',
                            'Jersey',
                            'Jordanie',
                            'Kazakhstan',
                            'Kenya',
                            'Kirghizstan',
                            'Kiribati',
                            'Kowe\u00eft',
                            'La R\u00e9union',
                            'Laos',
                            'Lesotho',
                            'Lettonie',
                            'Liban',
                            'Liberia',
                            'Libye',
                            'Liechtenstein',
                            'Lituanie',
                            'Luxembourg',
                            'Mac\u00e9doine du Nord',
                            'Madagascar',
                            'Malaisie',
                            'Malawi',
                            'Maldives',
                            'Mali',
                            'Malte',
                            'Maroc',
                            'Martinique',
                            'Maurice',
                            'Mauritanie',
                            'Mayotte',
                            'Mexique',
                            'Micron\u00e9sie',
                            'Moldavie',
                            'Monaco',
                            'Mongolie',
                            'Mont\u00e9n\u00e9gro',
                            'Montserrat',
                            'Mozambique',
                            'Myanmar (Birmanie)',
                            'Namibie',
                            'Nauru',
                            'N\u00e9pal',
                            'Nicaragua',
                            'Niger',
                            'Nigeria',
                            'Niue',
                            'Norv\u00e8ge',
                            'Nouvelle-Cal\u00e9donie',
                            'Nouvelle-Z\u00e9lande',
                            'Oman',
                            'Ouganda',
                            'Ouzb\u00e9kistan',
                            'Pakistan',
                            'Palaos',
                            'Panama',
                            'Papouasie-Nouvelle-Guin\u00e9e',
                            'Paraguay',
                            'Pays-Bas',
                            'Pays-Bas carib\u00e9ens',
                            'P\u00e9rou',
                            'Philippines',
                            'Pologne',
                            'Polyn\u00e9sie fran\u00e7aise',
                            'Porto Rico',
                            'Portugal',
                            'Qatar',
                            'R.A.S. chinoise de Hong Kong',
                            'R.A.S. chinoise de Macao',
                            'R\u00e9publique centrafricaine',
                            'R\u00e9publique dominicaine',
                            'Roumanie',
                            'Royaume-Uni',
                            'Russie',
                            'Rwanda',
                            'Sahara occidental',
                            'Saint-Barth\u00e9lemy',
                            'Saint-Christophe-et-Ni\u00e9v\u00e8s',
                            'Saint-Marin',
                            'Saint-Martin',
                            'Saint-Martin (partie n\u00e9erlandaise)',
                            'Saint-Pierre-et-Miquelon',
                            'Saint-Vincent-et-les Grenadines',
                            'Sainte-H\u00e9l\u00e8ne',
                            'Sainte-Lucie',
                            'Salvador',
                            'Samoa',
                            'Samoa am\u00e9ricaines',
                            'Sao Tom\u00e9-et-Principe',
                            'S\u00e9n\u00e9gal',
                            'Serbie',
                            'Seychelles',
                            'Sierra Leone',
                            'Singapour',
                            'Slovaquie',
                            'Slov\u00e9nie',
                            'Somalie',
                            'Soudan',
                            'Soudan du Sud',
                            'Sri Lanka',
                            'Su\u00e8de',
                            'Suisse',
                            'Suriname',
                            'Svalbard et Jan Mayen',
                            'Syrie',
                            'Tadjikistan',
                            'Ta\u00efwan',
                            'Tanzanie',
                            'Tchad',
                            'Tch\u00e9quie',
                            'Terres australes fran\u00e7aises',
                            'Territoire britannique de l\u2019oc\u00e9an Indien',
                            'Territoires palestiniens',
                            'Tha\u00eflande',
                            'Timor oriental',
                            'Togo',
                            'Tokelau',
                            'Tonga',
                            'Trinit\u00e9-et-Tobago',
                            'Tunisie',
                            'Turkm\u00e9nistan',
                            'Turquie',
                            'Tuvalu',
                            'Ukraine',
                            'Uruguay',
                            'Vanuatu',
                            'Venezuela',
                            'Vi\u00eat Nam',
                            'Wallis-et-Futuna',
                            'Y\u00e9men',
                            'Zambie',
                            'Zimbabwe',
                        ],
                    },
                    type: 'string',
                    title: 'Pays',
                    attr: {
                        'data-group': null,
                        'placeholder': 'Choisissez dans la liste d\u00e9roulante...',
                        'autocomplete': 'country-name',
                    },
                    propertyOrder: 4,
                },
                'sujet': {
                    items: {
                        type: 'string',
                        enum: [
                            'Don d\'objet',
                            'Renseignement',
                            'Objet perdu lors de ma visite',
                            'Droit de parole',
                            'Autre',
                        ],
                        enum_titles: [
                            'Don d\'objet',
                            'Renseignement',
                            'Objet perdu lors de ma visite',
                            'Droit de parole',
                            'Autre',
                        ],
                        options: {
                            enum_titles: [
                                'Don d\'objet',
                                'Renseignement',
                                'Objet perdu lors de ma visite',
                                'Droit de parole',
                                'Autre',
                            ],
                        },
                    },
                    minItems: 0,
                    uniqueItems: true,
                    type: 'array',
                    title: 'Sujet',
                    attr: {
                        'data-group': null,
                    },
                    propertyOrder: 5,
                },
                'votre_message': {
                    type: 'string',
                    title: 'Votre message',
                    attr: {
                        'data-group': null,
                    },
                    widget: 'textarea',
                    propertyOrder: 6,
                },
                'j_accepte_de_recevoir_des_informations_par_courrier_electronique_de_la_part_du_memorial_de_verdun_champ_de_bataille': {
                    type: 'boolean',
                    title: 'J\'accepte de recevoir des informations par courrier \u00e9lectronique de la part du M\u00e9morial de Verdun - champ de bataille',
                    attr: {
                        'data-group': null,
                    },
                    widget: 'checkbox',
                    propertyOrder: 7,
                },
                'g-recaptcha-response': {
                    type: 'string',
                    title: '',
                    propertyOrder: 8,
                },
            },
            required: [
                'adresse_email',
                'votre_message',
                'j_accepte_de_recevoir_des_informations_par_courrier_electronique_de_la_part_du_memorial_de_verdun_champ_de_bataille',
                'g-recaptcha-response',
            ],
        })
    }),
)
</script>

<template>
    <NuxtStory>
        <VForm :schema="schema" />
    </NuxtStory>
</template>
