# docker compose -f compose.prod.yml up --force-recreate
services:
    prod-node:
        build:
            context: .
            target: node-prod
        environment:
            NUXT_PUBLIC_API_URL: http://localhost:8088
            NUXT_PUBLIC_API_ENDPOINT_PREFIX: /api
            NUXT_PUBLIC_INTERVENTION_REQUEST_BASE_URL: http://localhost:8088/assets
            NUXT_PUBLIC_INTERVENTION_REQUEST_NO_PROCESS_BASE_URL: http://localhost:8088/assets/n
            NUXT_PUBLIC_INTERVENTION_REQUEST_IMAGES_PATH: /files

    prod-nginx:
        ports:
            - "8081:80/tcp"
        depends_on:
            - prod-node
        links:
            - prod-node:node
        build:
            context: .
            target: nginx-prod

    prod-maintenance:
        ports:
            - "8082:80/tcp"
        build:
            context: .
            target: nginx-maintenance
