overrides:
  fast-xml-builder: '>=1.1.7'
  postcss@<8.5.10: '>=8.5.10'

allowBuilds:
  '@parcel/watcher': true
  '@sentry/cli': true
  core-js: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
