export default {
    title: 'test_tous_les_types_de_champs',
    type: 'object',
    properties: {
        date_and_time: {
            type: 'string',
            title: 'Date and time',
            attr: {
                'data-group': null,
                placeholder: null,
            },
            widget: 'datetime',
            propertyOrder: 1,
        },
        date: {
            type: 'string',
            title: 'Date',
            attr: {
                'data-group': null,
                placeholder: null,
            },
            widget: 'date',
            propertyOrder: 2,
        },
        text: {
            type: 'string',
            title: 'Text',
        },
        textarea: {
            type: 'string',
            title: 'Textarea',
            attr: {
                'data-group': null,
                placeholder: null,
            },
            widget: 'textarea',
            propertyOrder: 3,
        },
        markdown: {
            type: 'string',
            title: 'Markdown',
            attr: {
                'data-group': null,
                placeholder: null,
            },
            widget: 'textarea',
            propertyOrder: 4,
        },
        boolean: {
            type: 'boolean',
            title: 'Boolean',
            attr: {
                'data-group': null,
                placeholder: null,
            },
            widget: 'checkbox',
            propertyOrder: 5,
        },
        number_int: {
            type: 'integer',
            title: 'Number int',
            attr: {
                'data-group': null,
                placeholder: null,
            },
            propertyOrder: 6,
        },
        number_float: {
            type: 'number',
            title: 'Number float',
            attr: {
                'data-group': null,
                placeholder: null,
            },
            propertyOrder: 7,
        },
        email: {
            type: 'string',
            title: 'Email',
            attr: {
                'data-group': null,
                placeholder: null,
            },
            widget: 'email',
            propertyOrder: 8,
        },
        choice_single: {
            enum: ['Value 1', 'Value 2', 'Value 3'],
            enum_titles: ['Value 1', 'Value 2', 'Value 3'],
            options: {
                enum_titles: ['Value 1', 'Value 2', 'Value 3'],
            },
            type: 'string',
            title: 'Choice single',
            attr: {
                'data-group': null,
                placeholder: null,
            },
            propertyOrder: 9,
        },
        choice_single_extended: {
            enum: ['Value 1', 'Value 2', 'Value 3'],
            enum_titles: ['Value 1', 'Value 2', 'Value 3'],
            options: {
                enum_titles: ['Value 1', 'Value 2', 'Value 3'],
            },
            type: 'string',
            widget: 'choice-expanded',
            title: 'Choice single extended',
            attr: {
                'data-group': null,
                placeholder: null,
            },
            propertyOrder: 10,
        },
        choice_multiple: {
            items: {
                type: 'string',
                enum: ['Value 1', 'Value 2', 'Value 3'],
                enum_titles: [
                    'Value 1',
                    'Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor',
                    'Nullam id dolor id nibh ultricies vehicula ut id elit',
                ],
                options: {
                    enum_titles: ['Value 1', 'Value 2', 'Value 3'],
                },
            },
            minItems: 0,
            uniqueItems: true,
            type: 'array',
            title: 'Choice multiple',
            attr: {
                'data-group': null,
                placeholder: null,
            },
            propertyOrder: 11,
        },
        choice_multiple_extended: {
            items: {
                type: 'string',
                enum: ['Value 1', 'Value 2', 'Value 3'],
                enum_titles: ['Value 1', 'Value 2', 'Value 3'],
                options: {
                    enum_titles: ['Value 1', 'Value 2', 'Value 3'],
                },
            },
            minItems: 0,
            uniqueItems: true,
            type: 'array',
            widget: 'choice-multiple-expanded',
            title: 'Choice multiple extended',
            attr: {
                'data-group': null,
                placeholder: null,
            },
            propertyOrder: 12,
        },
        countries: {
            enum: [
                'AF',
                'ZA',
                'AL',
                'DZ',
                'DE',
                'AD',
                'AO',
                'AI',
                'AQ',
                'AG',
                'SA',
                'AR',
                'AM',
                'AW',
                'AU',
                'AT',
                'AZ',
                'BS',
                'BH',
                'BD',
                'BB',
                'BE',
                'BZ',
                'BJ',
                'BM',
                'BT',
                'BY',
                'BO',
                'BA',
                'BW',
                'BR',
                'BN',
                'BG',
                'BF',
                'BI',
                'KH',
                'CM',
                'CA',
                'CV',
                'CL',
                'CN',
                'CY',
                'CO',
                'KM',
                'CG',
                'CD',
                'KP',
                'KR',
                'CR',
                'CI',
                'HR',
                'CU',
                'CW',
                'DK',
                'DJ',
                'DM',
                'EG',
                'AE',
                'EC',
                'ER',
                'ES',
                'EE',
                'SZ',
                'VA',
                'US',
                'ET',
                'FJ',
                'FI',
                'FR',
                'GA',
                'GM',
                'GE',
                'GS',
                'GH',
                'GI',
                'GR',
                'GD',
                'GL',
                'GP',
                'GU',
                'GT',
                'GG',
                'GN',
                'GQ',
                'GW',
                'GY',
                'GF',
                'HT',
                'HN',
                'HU',
                'BV',
                'CX',
                'IM',
                'NF',
                'AX',
                'KY',
                'CC',
                'CK',
                'FO',
                'HM',
                'FK',
                'MP',
                'MH',
                'UM',
                'PN',
                'SB',
                'TC',
                'VG',
                'VI',
                'IN',
                'ID',
                'IQ',
                'IR',
                'IE',
                'IS',
                'IL',
                'IT',
                'JM',
                'JP',
                'JE',
                'JO',
                'KZ',
                'KE',
                'KG',
                'KI',
                'KW',
                'RE',
                'LA',
                'LS',
                'LV',
                'LB',
                'LR',
                'LY',
                'LI',
                'LT',
                'LU',
                'MK',
                'MG',
                'MY',
                'MW',
                'MV',
                'ML',
                'MT',
                'MA',
                'MQ',
                'MU',
                'MR',
                'YT',
                'MX',
                'FM',
                'MD',
                'MC',
                'MN',
                'ME',
                'MS',
                'MZ',
                'MM',
                'NA',
                'NR',
                'NP',
                'NI',
                'NE',
                'NG',
                'NU',
                'NO',
                'NC',
                'NZ',
                'OM',
                'UG',
                'UZ',
                'PK',
                'PW',
                'PA',
                'PG',
                'PY',
                'NL',
                'BQ',
                'PE',
                'PH',
                'PL',
                'PF',
                'PR',
                'PT',
                'QA',
                'HK',
                'MO',
                'CF',
                'DO',
                'RO',
                'GB',
                'RU',
                'RW',
                'EH',
                'BL',
                'KN',
                'SM',
                'MF',
                'SX',
                'PM',
                'VC',
                'SH',
                'LC',
                'SV',
                'WS',
                'AS',
                'ST',
                'SN',
                'RS',
                'SC',
                'SL',
                'SG',
                'SK',
                'SI',
                'SO',
                'SD',
                'SS',
                'LK',
                'SE',
                'CH',
                'SR',
                'SJ',
                'SY',
                'TJ',
                'TW',
                'TZ',
                'TD',
                'CZ',
                'TF',
                'IO',
                'PS',
                'TH',
                'TL',
                'TG',
                'TK',
                'TO',
                'TT',
                'TN',
                'TM',
                'TR',
                'TV',
                'UA',
                'UY',
                'VU',
                'VE',
                'VN',
                'WF',
                'YE',
                'ZM',
                'ZW',
            ],
            enum_titles: [
                'Afghanistan',
                'Afrique du Sud',
                'Albanie',
                'Algérie',
                'Allemagne',
                'Andorre',
                'Angola',
                'Anguilla',
                'Antarctique',
                'Antigua-et-Barbuda',
                'Arabie saoudite',
                'Argentine',
                'Arménie',
                'Aruba',
                'Australie',
                'Autriche',
                'Azerbaïdjan',
                'Bahamas',
                'Bahreïn',
                'Bangladesh',
                'Barbade',
                'Belgique',
                'Belize',
                'Bénin',
                'Bermudes',
                'Bhoutan',
                'Biélorussie',
                'Bolivie',
                'Bosnie-Herzégovine',
                'Botswana',
                'Brésil',
                'Brunei',
                'Bulgarie',
                'Burkina Faso',
                'Burundi',
                'Cambodge',
                'Cameroun',
                'Canada',
                'Cap-Vert',
                'Chili',
                'Chine',
                'Chypre',
                'Colombie',
                'Comores',
                'Congo-Brazzaville',
                'Congo-Kinshasa',
                'Corée du Nord',
                'Corée du Sud',
                'Costa Rica',
                'Côte d’Ivoire',
                'Croatie',
                'Cuba',
                'Curaçao',
                'Danemark',
                'Djibouti',
                'Dominique',
                'Égypte',
                'Émirats arabes unis',
                'Équateur',
                'Érythrée',
                'Espagne',
                'Estonie',
                'Eswatini',
                'État de la Cité du Vatican',
                'États-Unis',
                'Éthiopie',
                'Fidji',
                'Finlande',
                'France',
                'Gabon',
                'Gambie',
                'Géorgie',
                'Géorgie du Sud-et-les Îles Sandwich du Sud',
                'Ghana',
                'Gibraltar',
                'Grèce',
                'Grenade',
                'Groenland',
                'Guadeloupe',
                'Guam',
                'Guatemala',
                'Guernesey',
                'Guinée',
                'Guinée équatoriale',
                'Guinée-Bissau',
                'Guyana',
                'Guyane française',
                'Haïti',
                'Honduras',
                'Hongrie',
                'Île Bouvet',
                'Île Christmas',
                'Île de Man',
                'Île Norfolk',
                'Îles Åland',
                'Îles Caïmans',
                'Îles Cocos',
                'Îles Cook',
                'Îles Féroé',
                'Îles Heard-et-MacDonald',
                'Îles Malouines',
                'Îles Mariannes du Nord',
                'Îles Marshall',
                'Îles mineures éloignées des États-Unis',
                'Îles Pitcairn',
                'Îles Salomon',
                'Îles Turques-et-Caïques',
                'Îles Vierges britanniques',
                'Îles Vierges des États-Unis',
                'Inde',
                'Indonésie',
                'Irak',
                'Iran',
                'Irlande',
                'Islande',
                'Israël',
                'Italie',
                'Jamaïque',
                'Japon',
                'Jersey',
                'Jordanie',
                'Kazakhstan',
                'Kenya',
                'Kirghizstan',
                'Kiribati',
                'Koweït',
                'La Réunion',
                'Laos',
                'Lesotho',
                'Lettonie',
                'Liban',
                'Liberia',
                'Libye',
                'Liechtenstein',
                'Lituanie',
                'Luxembourg',
                'Macédoine du Nord',
                'Madagascar',
                'Malaisie',
                'Malawi',
                'Maldives',
                'Mali',
                'Malte',
                'Maroc',
                'Martinique',
                'Maurice',
                'Mauritanie',
                'Mayotte',
                'Mexique',
                'Micronésie',
                'Moldavie',
                'Monaco',
                'Mongolie',
                'Monténégro',
                'Montserrat',
                'Mozambique',
                'Myanmar (Birmanie)',
                'Namibie',
                'Nauru',
                'Népal',
                'Nicaragua',
                'Niger',
                'Nigeria',
                'Niue',
                'Norvège',
                'Nouvelle-Calédonie',
                'Nouvelle-Zélande',
                'Oman',
                'Ouganda',
                'Ouzbékistan',
                'Pakistan',
                'Palaos',
                'Panama',
                'Papouasie-Nouvelle-Guinée',
                'Paraguay',
                'Pays-Bas',
                'Pays-Bas caribéens',
                'Pérou',
                'Philippines',
                'Pologne',
                'Polynésie française',
                'Porto Rico',
                'Portugal',
                'Qatar',
                'R.A.S. chinoise de Hong Kong',
                'R.A.S. chinoise de Macao',
                'République centrafricaine',
                'République dominicaine',
                'Roumanie',
                'Royaume-Uni',
                'Russie',
                'Rwanda',
                'Sahara occidental',
                'Saint-Barthélemy',
                'Saint-Christophe-et-Niévès',
                'Saint-Marin',
                'Saint-Martin',
                'Saint-Martin (partie néerlandaise)',
                'Saint-Pierre-et-Miquelon',
                'Saint-Vincent-et-les Grenadines',
                'Sainte-Hélène',
                'Sainte-Lucie',
                'Salvador',
                'Samoa',
                'Samoa américaines',
                'Sao Tomé-et-Principe',
                'Sénégal',
                'Serbie',
                'Seychelles',
                'Sierra Leone',
                'Singapour',
                'Slovaquie',
                'Slovénie',
                'Somalie',
                'Soudan',
                'Soudan du Sud',
                'Sri Lanka',
                'Suède',
                'Suisse',
                'Suriname',
                'Svalbard et Jan Mayen',
                'Syrie',
                'Tadjikistan',
                'Taïwan',
                'Tanzanie',
                'Tchad',
                'Tchéquie',
                'Terres australes françaises',
                'Territoire britannique de l’océan Indien',
                'Territoires palestiniens',
                'Thaïlande',
                'Timor oriental',
                'Togo',
                'Tokelau',
                'Tonga',
                'Trinité-et-Tobago',
                'Tunisie',
                'Turkménistan',
                'Turquie',
                'Tuvalu',
                'Ukraine',
                'Uruguay',
                'Vanuatu',
                'Venezuela',
                'Viêt Nam',
                'Wallis-et-Futuna',
                'Yémen',
                'Zambie',
                'Zimbabwe',
            ],
            options: {
                enum_titles: [
                    'Afghanistan',
                    'Afrique du Sud',
                    'Albanie',
                    'Algérie',
                    'Allemagne',
                    'Andorre',
                    'Angola',
                    'Anguilla',
                    'Antarctique',
                    'Antigua-et-Barbuda',
                    'Arabie saoudite',
                    'Argentine',
                    'Arménie',
                    'Aruba',
                    'Australie',
                    'Autriche',
                    'Azerbaïdjan',
                    'Bahamas',
                    'Bahreïn',
                    'Bangladesh',
                    'Barbade',
                    'Belgique',
                    'Belize',
                    'Bénin',
                    'Bermudes',
                    'Bhoutan',
                    'Biélorussie',
                    'Bolivie',
                    'Bosnie-Herzégovine',
                    'Botswana',
                    'Brésil',
                    'Brunei',
                    'Bulgarie',
                    'Burkina Faso',
                    'Burundi',
                    'Cambodge',
                    'Cameroun',
                    'Canada',
                    'Cap-Vert',
                    'Chili',
                    'Chine',
                    'Chypre',
                    'Colombie',
                    'Comores',
                    'Congo-Brazzaville',
                    'Congo-Kinshasa',
                    'Corée du Nord',
                    'Corée du Sud',
                    'Costa Rica',
                    'Côte d’Ivoire',
                    'Croatie',
                    'Cuba',
                    'Curaçao',
                    'Danemark',
                    'Djibouti',
                    'Dominique',
                    'Égypte',
                    'Émirats arabes unis',
                    'Équateur',
                    'Érythrée',
                    'Espagne',
                    'Estonie',
                    'Eswatini',
                    'État de la Cité du Vatican',
                    'États-Unis',
                    'Éthiopie',
                    'Fidji',
                    'Finlande',
                    'France',
                    'Gabon',
                    'Gambie',
                    'Géorgie',
                    'Géorgie du Sud-et-les Îles Sandwich du Sud',
                    'Ghana',
                    'Gibraltar',
                    'Grèce',
                    'Grenade',
                    'Groenland',
                    'Guadeloupe',
                    'Guam',
                    'Guatemala',
                    'Guernesey',
                    'Guinée',
                    'Guinée équatoriale',
                    'Guinée-Bissau',
                    'Guyana',
                    'Guyane française',
                    'Haïti',
                    'Honduras',
                    'Hongrie',
                    'Île Bouvet',
                    'Île Christmas',
                    'Île de Man',
                    'Île Norfolk',
                    'Îles Åland',
                    'Îles Caïmans',
                    'Îles Cocos',
                    'Îles Cook',
                    'Îles Féroé',
                    'Îles Heard-et-MacDonald',
                    'Îles Malouines',
                    'Îles Mariannes du Nord',
                    'Îles Marshall',
                    'Îles mineures éloignées des États-Unis',
                    'Îles Pitcairn',
                    'Îles Salomon',
                    'Îles Turques-et-Caïques',
                    'Îles Vierges britanniques',
                    'Îles Vierges des États-Unis',
                    'Inde',
                    'Indonésie',
                    'Irak',
                    'Iran',
                    'Irlande',
                    'Islande',
                    'Israël',
                    'Italie',
                    'Jamaïque',
                    'Japon',
                    'Jersey',
                    'Jordanie',
                    'Kazakhstan',
                    'Kenya',
                    'Kirghizstan',
                    'Kiribati',
                    'Koweït',
                    'La Réunion',
                    'Laos',
                    'Lesotho',
                    'Lettonie',
                    'Liban',
                    'Liberia',
                    'Libye',
                    'Liechtenstein',
                    'Lituanie',
                    'Luxembourg',
                    'Macédoine du Nord',
                    'Madagascar',
                    'Malaisie',
                    'Malawi',
                    'Maldives',
                    'Mali',
                    'Malte',
                    'Maroc',
                    'Martinique',
                    'Maurice',
                    'Mauritanie',
                    'Mayotte',
                    'Mexique',
                    'Micronésie',
                    'Moldavie',
                    'Monaco',
                    'Mongolie',
                    'Monténégro',
                    'Montserrat',
                    'Mozambique',
                    'Myanmar (Birmanie)',
                    'Namibie',
                    'Nauru',
                    'Népal',
                    'Nicaragua',
                    'Niger',
                    'Nigeria',
                    'Niue',
                    'Norvège',
                    'Nouvelle-Calédonie',
                    'Nouvelle-Zélande',
                    'Oman',
                    'Ouganda',
                    'Ouzbékistan',
                    'Pakistan',
                    'Palaos',
                    'Panama',
                    'Papouasie-Nouvelle-Guinée',
                    'Paraguay',
                    'Pays-Bas',
                    'Pays-Bas caribéens',
                    'Pérou',
                    'Philippines',
                    'Pologne',
                    'Polynésie française',
                    'Porto Rico',
                    'Portugal',
                    'Qatar',
                    'R.A.S. chinoise de Hong Kong',
                    'R.A.S. chinoise de Macao',
                    'République centrafricaine',
                    'République dominicaine',
                    'Roumanie',
                    'Royaume-Uni',
                    'Russie',
                    'Rwanda',
                    'Sahara occidental',
                    'Saint-Barthélemy',
                    'Saint-Christophe-et-Niévès',
                    'Saint-Marin',
                    'Saint-Martin',
                    'Saint-Martin (partie néerlandaise)',
                    'Saint-Pierre-et-Miquelon',
                    'Saint-Vincent-et-les Grenadines',
                    'Sainte-Hélène',
                    'Sainte-Lucie',
                    'Salvador',
                    'Samoa',
                    'Samoa américaines',
                    'Sao Tomé-et-Principe',
                    'Sénégal',
                    'Serbie',
                    'Seychelles',
                    'Sierra Leone',
                    'Singapour',
                    'Slovaquie',
                    'Slovénie',
                    'Somalie',
                    'Soudan',
                    'Soudan du Sud',
                    'Sri Lanka',
                    'Suède',
                    'Suisse',
                    'Suriname',
                    'Svalbard et Jan Mayen',
                    'Syrie',
                    'Tadjikistan',
                    'Taïwan',
                    'Tanzanie',
                    'Tchad',
                    'Tchéquie',
                    'Terres australes françaises',
                    'Territoire britannique de l’océan Indien',
                    'Territoires palestiniens',
                    'Thaïlande',
                    'Timor oriental',
                    'Togo',
                    'Tokelau',
                    'Tonga',
                    'Trinité-et-Tobago',
                    'Tunisie',
                    'Turkménistan',
                    'Turquie',
                    'Tuvalu',
                    'Ukraine',
                    'Uruguay',
                    'Vanuatu',
                    'Venezuela',
                    'Viêt Nam',
                    'Wallis-et-Futuna',
                    'Yémen',
                    'Zambie',
                    'Zimbabwe',
                ],
            },
            attr: {
                placeholder: 'Select a country',
            },
            type: 'string',
            title: 'Countries',
            propertyOrder: 13,
        },
        upload: {
            type: 'string',
            title: 'Documents',
            attr: {
                'data-group': null,
                placeholder: null,
            },
            widget: 'file',
            propertyOrder: 14,
        },
        'g-recaptcha-response': {
            type: 'string',
            title: 'recaptcha',
            propertyOrder: 15,
        },
    },
    required: ['g-recaptcha-response', 'email'],
}
